version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "libraries"
  build:
    commands:
      - zip -r9 cplf1.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name LF1 --zip-file fileb://cplf1.zip